return {
    cmd = { 'harper-ls', '--stdio' },
    filetypes = {
        'c',
        'cmake',
        'cpp',
        'cs',
        'dart',
        'gitcommit',
        'go',
        'haskell',
        'html',
        'java',
        'javascript',
        'lua',
        'markdown',
        'nix',
        'php',
        'python',
        'ruby',
        'rust',
        'swift',
        'toml',
        'typescript',
        'typescriptreact',
        'typst',
    },
}
