" ---------- Vim Defaults ----------
let mapleader = '\'             " Leader is backslash

if &loadplugins && !has('packages')
    if has("vim_starting")
        runtime! pack/vendor/opt/pathogen/autoload/pathogen.vim
    endif

    execute pathogen#infect()
endif

filetype plugin on              " Enable plugins to detect file types

" ---------- Colors ----------
syntax enable                   " Enable syntax processing
set background=dark             " Set a dark background profile
try
    let g:hybrid_custom_term_colors = 1
    colorscheme hybrid              " Set color scheme
catch
    colorscheme peachpuff
endtry

" Only do this part when compiled with support for autocommands
if has("autocmd")
    " Enable file type detection
    filetype on
endif

" ---------- Indentation ----------
filetype indent on              " Indent depends on filetype

" ---------- Spelling ----------
if has("spell")
    " Change menu color
    highlight PmenuSel ctermfg=black ctermbg=lightgray
endif

" ---------- Local Configurations ----------
if filereadable(glob($MYVIMRC . ".local"))
    source $MYVIMRC.local
endif
